baseURL = "https://elu00.github.io/LatexQuickStart"
title = "Latex Quickstart"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true

publishDir = "docs"
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

# Everything below this are Site Params

[params]
  author = "Ethan Lu"
  searchPlaceholder = "Search the docs ..."
  repo = "https://github.com/elu00/LatexQuickstart"

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  enableDarkMode = true
  [params.logo]
    lightMode = "compose.svg"
    darkMode = "compose-light.svg"

  [params.source]
    name = "GitHub"
    icon = "github.svg"
    url = "https://github.com/elu00/Latex-Quickstart"

